version: "3.8"

services:
  # server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: portfolio-web-server
    container_name: portfolio-web-server
    ports:
      - "80:80" # Connect localhost 80 port to container 80 port
      - "443:443"
    networks:
      - app-network
    volumes:
      - web-root:/var/www/html
      - ./server/nginx/${BUILD_TARGET}/:/etc/nginx/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - client
      - filestream
  # filestream service
  filestream:
    build:
      context: ./filestream
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    image: azharalifauzi/portfolio-web-filestream
    container_name: portfolio-web-filestream
    ports:
      - "4000"
    volumes:
      - ./filestream/:/app
    networks:
      - app-network
    environment:
      - PORT=4000
  # api service
  api:
    build:
      context: ./api
      target: ${BUILD_TARGET}
      dockerfile: Dockerfile
    image: azharalifauzi/portfolio-web-api
    container_name: portfolio-web-api
    volumes:
      - ./api/:/app
      - /app/node_modules
    ports:
      - "5000"
    depends_on:
      - postgres
    environment:
      - GRAPHQL_SECRET_KEY=${GRAPHQL_SECRET_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - app-network
  # postgres service
  postgres:
    image: postgres
    volumes:
      - data-volume:/var/lib/postgresql/data/
    ports:
      - "8080:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  # client service
  client:
    build:
      context: ./client
      target: ${BUILD_TARGET}
      dockerfile: Dockerfile
    image: azharalifauzi/portfolio-web-client
    container_name: portfolio-web-client
    volumes:
      - type: bind
        source: ./client/
        target: /app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
  #certbot service
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - server
    command: certonly --webroot --webroot-path=/var/www/html --email azharalifauzi@gmail.com --agree-tos --no-eff-email --force-renewal -d azharalifauzi.dev -d www.azharalifauzi.dev

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
