name: Docker Compose Actions Workflow
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build the stack and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build graphql client filestream
        env:
          BUILD_TARGET: production
          GRAPHQL_CLIENT_URL: https://azharalifauzi.dev/graphql/
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: azharalifauzi
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        run: docker-compose push graphql client filestream
  deploy:
    name: Deploy to Digitalocean
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd portfolio-web/
            docker-compose pull graphql client filestream
            git pull origin master
            docker-compose rm --stop --force graphql client filestream
            docker-compose up -d graphql client filestream
            docker-compose restart server
